import httpService from './httpService'
import SERVICE_URL from '@/constants/serviceUrls'

const { KEYCLOAK_WRAPPER } = SERVICE_URL;

const mockedResponse = {
  "status": 200,
  "message": "Logged in successfully",
  "data": {
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJEZFFMLXpjcTJMNTBOUU1PWU9QRFR6NlhzV1hNcHhzOFRUa1BDQl9FY0FvIn0.eyJleHAiOjE2OTU5OTQyMjksImlhdCI6MTY5NTk4NzAyOSwianRpIjoiNjEzMzYwY2QtNTY3MC00ZmUwLTlmODQtMmE3MjBhYjEwOWZkIiwiaXNzIjoiaHR0cHM6Ly9pZHAtZGV2My1ob3JzZS5zYWFsLmFpL2F1dGgvcmVhbG1zL1NhYWwtSG9yc2UiLCJhdWQiOlsicmVhbG0tbWFuYWdlbWVudCIsImF1Y3Rpb24tY2xpZW50IiwiaHlwby1jbGllbnQiLCJicm9rZXIiLCJhY2NvdW50IiwiYW5hbHl0aWNzLWNsaWVudCJdLCJzdWIiOiJkMTJmOGRhYy0xNjcwLTRhODctOGU1MC0xMjJkODk3ZDk5YmEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjbGllbnRfMTIzNCIsInNlc3Npb25fc3RhdGUiOiJmOWFkNWEwOC1iNDA2LTQ3MDAtOTRmOC0xYmJjMTgwOGVkMjkiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJBZG1pbiIsImRlZmF1bHQtcm9sZXMtc2FhbC1ob3JzZSJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImNsaWVudF8xMjM0Ijp7InJvbGVzIjpbIlVzZXIiXX0sInJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYXVjdGlvbi1jbGllbnQiOnsicm9sZXMiOlsiVXNlciJdfSwiaHlwby1jbGllbnQiOnsicm9sZXMiOlsiVXNlciJdfSwiYnJva2VyIjp7InJvbGVzIjpbInJlYWQtdG9rZW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LWFwcGxpY2F0aW9ucyIsInZpZXctY29uc2VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwiZGVsZXRlLWFjY291bnQiLCJtYW5hZ2UtY29uc2VudCIsInZpZXctcHJvZmlsZSJdfSwiYW5hbHl0aWNzLWNsaWVudCI6eyJyb2xlcyI6WyJVc2VyIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiZjlhZDVhMDgtYjQwNi00NzAwLTk0ZjgtMWJiYzE4MDhlZDI5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJBZG1pbiBBZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFudWoua3VtYXIxQHN1Y2Nlc3NpdmUudGVjaCIsImdpdmVuX25hbWUiOiJBZG1pbiIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFudWoua3VtYXIxQHN1Y2Nlc3NpdmUudGVjaCJ9.RqDXnGOZL9zn3wRDA1QU16dJWaQh3DPIGpIszESh6FT3lF3Sokn-AP2mSH50DlZIQPrEHJTFDOHRe2WyNJ2NswCOjOQz6hrkBNocZRy3p81EhtLkkeaDGRfeiHOPC4saPOYCIdsIDi6OtrOAKDVAHFyEV5FL3uQKoPYOcpwB2OYCQs-bLaVTerh6unIddctoLjDS2reV1nTLMNSPEcZixuzLcFKIolikCiknCA6j3gEaUEJM0_DNn9AdmQaaYQ2XVhaLQnWMi8IUKndK0N_cJoltvbtMrJDDE9C1Z04LeQJE0bZKw5p7Ki7jEX_MenEIIsqPR4XpwpJJJd2c8VDKLQ",
    "expires_in": 7200,
    "refresh_expires_in": 18000,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzNDcwOWY1OS1jNjE0LTQ1NWUtODkyYy1iMTQxYWZhMmZmZTkifQ.eyJleHAiOjE2OTYwMDUwMjksImlhdCI6MTY5NTk4NzAyOSwianRpIjoiOTgzNTM5ZjctZjI0NS00MzIyLWE5NTEtYzVlNzUwMWQyODgwIiwiaXNzIjoiaHR0cHM6Ly9pZHAtZGV2My1ob3JzZS5zYWFsLmFpL2F1dGgvcmVhbG1zL1NhYWwtSG9yc2UiLCJhdWQiOiJodHRwczovL2lkcC1kZXYzLWhvcnNlLnNhYWwuYWkvYXV0aC9yZWFsbXMvU2FhbC1Ib3JzZSIsInN1YiI6ImQxMmY4ZGFjLTE2NzAtNGE4Ny04ZTUwLTEyMmQ4OTdkOTliYSIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJjbGllbnRfMTIzNCIsInNlc3Npb25fc3RhdGUiOiJmOWFkNWEwOC1iNDA2LTQ3MDAtOTRmOC0xYmJjMTgwOGVkMjkiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJmOWFkNWEwOC1iNDA2LTQ3MDAtOTRmOC0xYmJjMTgwOGVkMjkifQ.3_MIva2gEh8q3Fcugj15KAK9hTYydfDrDoLEEX0LhY8",
    "token_type": "Bearer",
    "not-before-policy": 1694700077,
    "session_state": "f9ad5a08-b406-4700-94f8-1bbc1808ed29",
    "scope": "profile email",
    "user": {
      "name": "Admin Admin",
      "email": "anuj.kumar1@successive.tech"
    }
  }
}
// signIn API 
export const signInApi = async (details) =>{
  return Promise.resolve(mockedResponse)
}

//forgotPassword API
export const forgotPasswordApi = async (details) =>{
  return httpService.post({ url: `${KEYCLOAK_WRAPPER}forgot-password`, data: details, isCacheEnabled: false })
}
