export const tokens = {
  "light": {
    "colors": {
      "Brand-gold.1": "#F8F3EB",
      "Brand-gold.2": "#EDE3CF",
      "Brand-gold.3": "#E0CDA8",
      "Brand-gold.4": "#D1B580",
      "Brand-gold.5": "#C39F59",
      "Brand-gold.6": "#B68A35",
      "Brand-gold.7": "#9B752D",
      "Brand-gold.8": "#816226",
      "Brand-gold.9": "#684F1E",
      "Brand-gold.10": "#523E18",
      "purple.1": "#f9f0ff",
      "purple.2": "#efdbff",
      "purple.3": "#d3adf7",
      "purple.4": "#b37feb",
      "purple.5": "#9254de",
      "purple.6": "#722ed1",
      "purple.7": "#531dab",
      "purple.8": "#391085",
      "purple.9": "#22075e",
      "purple.10": "#120338",
      "cyan.1": "#e6fffb",
      "cyan.2": "#b5f5ec",
      "cyan.3": "#87e8de",
      "cyan.4": "#5cdbd3",
      "cyan.5": "#36cfc9",
      "cyan.6": "#13c2c2",
      "cyan.7": "#08979c",
      "cyan.8": "#006d75",
      "cyan.9": "#00474f",
      "cyan.10": "#002329",
      "green.1": "#f6ffed",
      "green.2": "#d9f7be",
      "green.3": "#b7eb8f",
      "green.4": "#95de64",
      "green.5": "#73d13d",
      "green.6": "#52c41a",
      "green.7": "#389e0d",
      "green.8": "#237804",
      "green.9": "#135200",
      "green.10": "#092b00",
      "magenta.1": "#fff0f6",
      "magenta.2": "#ffd6e7",
      "magenta.3": "#ffadd2",
      "magenta.4": "#ff85c0",
      "magenta.5": "#f759ab",
      "magenta.6": "#eb2f96",
      "magenta.7": "#c41d7f",
      "magenta.8": "#9e1068",
      "magenta.9": "#780650",
      "magenta.10": "#520339",
      "red.1": "#fff1f0",
      "red.2": "#ffccc7",
      "red.3": "#ffa39e",
      "red.4": "#ff7875",
      "red.5": "#ff4d4f",
      "red.6": "#f5222d",
      "red.7": "#cf1322",
      "red.8": "#a8071a",
      "red.9": "#820014",
      "red.10": "#5c0011",
      "orange.1": "#fff7e6",
      "orange.2": "#ffe7ba",
      "orange.3": "#ffd591",
      "orange.4": "#ffc069",
      "orange.5": "#ffa940",
      "orange.6": "#fa8c16",
      "orange.7": "#d46b08",
      "orange.8": "#ad4e00",
      "orange.9": "#873800",
      "orange.10": "#612500",
      "yellow.1": "#feffe6",
      "yellow.2": "#ffffb8",
      "yellow.3": "#fffb8f",
      "yellow.4": "#fff566",
      "yellow.5": "#ffec3d",
      "yellow.6": "#fadb14",
      "yellow.7": "#d4b106",
      "yellow.8": "#ad8b00",
      "yellow.9": "#876800",
      "yellow.10": "#614700",
      "volcano.1": "#fff2e8",
      "volcano.2": "#ffd8bf",
      "volcano.3": "#ffbb96",
      "volcano.4": "#ff9c6e",
      "volcano.5": "#ff7a45",
      "volcano.6": "#fa541c",
      "volcano.7": "#d4380d",
      "volcano.8": "#ad2102",
      "volcano.9": "#871400",
      "volcano.10": "#610b00",
      "geekblue.1": "#f0f5ff",
      "geekblue.2": "#d6e4ff",
      "geekblue.3": "#adc6ff",
      "geekblue.4": "#85a5ff",
      "geekblue.5": "#597ef7",
      "geekblue.6": "#2f54eb",
      "geekblue.7": "#1d39c4",
      "geekblue.8": "#10239e",
      "geekblue.9": "#061178",
      "geekblue.10": "#030852",
      "lime.1": "#fcffe6",
      "lime.2": "#f4ffb8",
      "lime.3": "#eaff8f",
      "lime.4": "#d3f261",
      "lime.5": "#bae637",
      "lime.6": "#a0d911",
      "lime.7": "#7cb305",
      "lime.8": "#5b8c00",
      "lime.9": "#3f6600",
      "lime.10": "#254000",
      "gold.1": "#fffbe6",
      "gold.2": "#fff1b8",
      "gold.3": "#ffe58f",
      "gold.4": "#ffd666",
      "gold.5": "#ffc53d",
      "gold.6": "#faad14",
      "gold.7": "#d48806",
      "gold.8": "#ad6800",
      "gold.9": "#874d00",
      "gold.10": "#613400",
      "blue.1": "#e6f4ff",
      "blue.2": "#bae0ff",
      "blue.3": "#91caff",
      "blue.4": "#69b1ff",
      "blue.5": "#4096ff",
      "blue.6": "#1677ff",
      "blue.7": "#0958d9",
      "blue.8": "#003eb3",
      "blue.9": "#002c8c",
      "blue.10": "#001d66"
    },
    "seed": {
      "colorTextBase": "#000",
      "colorTextLightSolid": "#ffffff",
      "colorBgBase": "#ffffff",
      "fontSize": 14,
      "lineWidth": 1,
      "borderRadius": 6,
      "sizeUnit": 4,
      "sizePopupArrow": 16,
      "controlHeight": 32,
      "opacityImage": 1,
      "sizeStep": 4,
      "colorPrimary": "#B68A35",
      "colorError": "#ff4d4f",
      "colorWarning": "#fa8c16",
      "colorSuccess": "#52c41a",
      "colorInfo": "#B68A35"
    },
    "map": {
      "sizeXXL": 48,
      "sizeXL": 32,
      "sizeLG": 24,
      "sizeMD": 20,
      "sizeMS": 16,
      "size": 16,
      "sizeSM": 12,
      "sizeXS": 8,
      "sizeXXS": 4,
      "controlHeightSM": 24,
      "controlHeightXS": 16,
      "controlHeightLG": 40,
      "borderRadiusXS": 2,
      "borderRadiusSM": 4,
      "borderRadiusLG": 8,
      "borderRadiusOuter": 4,
      "colorText": "rgba(0, 0, 0, 0.88)",
      "colorTextSecondary": "rgba(0, 0, 0, 0.65)",
      "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
      "colorTextQuaternary": "#4F4F4F",
      "colorFill": "rgba(0, 0, 0, 0.15)",
      "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
      "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
      "colorBgContainer": "#ffffff",
      "colorFillQuaternary": "rgba(0, 0, 0, 0.02)",
      "colorBgLayout": "#f5f5f5",
      "colorBgElevated": "#ffffff",
      "colorBgSpotlight": "#000",
      "colorBorder": "rgba(0, 0, 0, 0.15)",
      "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
      "colorSplit": "rgba(0, 0, 0, 0.06)",
      "colorPrimaryBg": "#F8F3EB",
      "colorPrimaryBgHover": "#EDE3CF",
      "colorPrimaryBorder": "#E0CDA8",
      "colorPrimaryBorderHover": "#D1B580",
      "colorPrimaryHover": "#C39F59",
      "colorPrimaryBase": "#B68A35",
      "colorPrimaryActive": "#9B752D",
      "colorPrimaryTextHover": "#816226",
      "colorPrimaryText": "#684F1E",
      "colorPrimaryTextActive": "#523E18",
      "colorSuccessBg": "#f6ffed",
      "colorSuccessBgHover": "#d9f7be",
      "colorSuccessBorder": "#b7eb8f",
      "colorSuccessBorderHover": "#95de64",
      "colorSuccessHover": "#73d13d",
      "colorSuccessBase": "#52c41a",
      "colorSuccessActive": "#389e0d",
      "colorSuccessTextHover": "#237804",
      "colorSuccessText": "#135200",
      "colorSuccessTextActive": "#092b00",
      "colorWarningBg": "#fff7e6",
      "colorWarningBgHover": "#ffe7ba",
      "colorWarningBorder": "#ffd591",
      "colorWarningBorderHover": "#ffc069",
      "colorWarningHover": "#ffa940",
      "colorWarningBase": "#fa8c16",
      "colorWarningActive": "#d46b08",
      "colorWarningTextHover": "#ad4e00",
      "colorWarningText": "#873800",
      "colorWarningTextActive": "#612500",
      "colorErrorBg": "#fff1f0",
      "colorErrorBgHover": "#ffccc7",
      "colorErrorBorder": "#ffa39e",
      "colorErrorBorderHover": "#ff7875",
      "colorErrorHover": "#ff7875",
      "colorErrorBase": "#ff4d4f",
      "colorErrorActive": "#cf1322",
      "colorErrorTextHover": "#a8071a",
      "colorErrorText": "#820014",
      "colorErrorTextActive": "#5c0011",
      "colorInfoBg": "#F8F3EB",
      "colorInfoBgHover": "#EDE3CF",
      "colorInfoBorder": "#E0CDA8",
      "colorInfoBorderHover": "#D1B580",
      "colorInfoHover": "#C39F59",
      "colorInfoBase": "#B68A35",
      "colorInfoActive": "#9B752D",
      "colorInfoTextHover": "#816226",
      "colorInfoText": "#684F1E",
      "colorInfoTextActive": "#523E18",
      "colorBgMask": "rgba(0, 0, 0, 0.45)",
      "stepsDotSize": 8,
      "stepsCurrentDotSize": 10,
      "rateStarSize": 20,
      "lineWidthBold": 2
    },
    "alias": {
      "colorFillContent": "rgba(0, 0, 0, 0.06)",
      "colorFillContentHover": "rgba(0, 0, 0, 0.15)",
      "colorFillAlter": "rgba(0, 0, 0, 0.02)",
      "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
      "colorBorderBg": "#ffffff",
      "colorTextPlaceholder": "#4F4F4F",
      "colorTextDisabled": "rgba(0,0,0,0.25)",
      "colorTextHeading": "rgba(0, 0, 0, 0.88)",
      "colorTextLabel": "rgba(0, 0, 0, 0.65)",
      "colorTextDescription": "rgba(0, 0, 0, 0.45)",
      "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
      "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
      "colorIcon": "rgba(0, 0, 0, 0.45)",
      "colorIconHover": "rgba(0, 0, 0, 0.88)",
      "colorLink": "#B68A35",
      "colorLinkHover": "#C39F59",
      "colorLinkActive": "#9B752D",
      "colorHighlight": "#ff7875",
      "controlOutline": "rgba(5, 145, 255, 0.1)",
      "colorWarningOutline": "#fff7e6",
      "colorErrorOutline": "#fff1f0",
      "fontSizeSM": 12,
      "fontSizeLG": 16,
      "fontSizeXL": 20,
      "fontSizeIcon": 12,
      "fontSizeHeading1": 38,
      "fontSizeHeading2": 30,
      "fontSizeHeading3": 24,
      "fontSizeHeading4": 20,
      "fontSizeHeading5": 16,
      "fontWeightNormal": 400,
      "fontWeightStrong": 600,
      "controlLineWidth": 1,
      "controlOutlineWidth": 2,
      "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
      "controlItemBgActive": "#F8F3EB",
      "controlItemBgActiveHover": "#EDE3CF",
      "controlInteractiveSize": 16,
      "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
      "controlTmpOutline": "rgba(0, 0, 0, 0.02)",
      "opacityLoading": 0.65,
      "padding": 16,
      "paddingMD": 20,
      "paddingSM": 12,
      "paddingXS": 8,
      "paddingXXS": 4,
      "paddingLG": 24,
      "paddingXL": 32,
      "paddingXXL": 48,
      "margin": 16,
      "marginSM": 12,
      "marginXS": 8,
      "marginXXS": 4,
      "marginLG": 24,
      "marginXL": 32,
      "marginXXL": 48,
      "controlPaddingHorizontal": 12,
      "controlPaddingHorizontalSM": 8,
      "paddingContentHorizontalLG": 24,
      "paddingContentVerticalLG": 16,
      "paddingContentHorizontal": 16,
      "paddingContentVertical": 12,
      "paddingContentHorizontalSM": 16,
      "paddingContentVerticalSM": 8,
      "colorItemText": "rgba(255, 255, 255, 0.65)",
      "colorItemTextDisabled": "rgba(255, 255, 255, 0.25)",
      "tooltipBg": "rgba(0, 0, 0, 0.88)",
      "segmentedBgColorSelected": "#ffffff",
      "segmentedGroupBg": "rgba(0, 0, 0, 0.04)",
      "colorMenuDarkBg": "141414",
      "colorMenuSubItemBg": "#222222",
      "paddingTooltipContentVertical": 6,
      "screenXS": 480,
      "screenSM": 576,
      "screenMD": 768,
      "screenLG": 992,
      "screenXL": 1200,
      "screenXXL": 1600,
      "screenXSMin": 480,
      "screenXSMax": 575,
      "screenSMMin": 576,
      "screenSMMax": 767,
      "screenMDMin": 768,
      "screenMDMax": 991,
      "screenLGMin": 992,
      "screenLGMax": 1199,
      "screenXLMin": 1200,
      "screenXLMax": 1599,
      "screenXXLMin": 1600
    },
    "components": {
      "Anchor": {
        "colorPrimary": "#B68A35",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "lineWidthBold": 2,
        "padding": 16,
        "paddingXXS": 4
      },
      "Breadcrumb": {
        "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
        "colorPrimaryBorder": "#E0CDA8",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "borderRadiusSM": 4,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingXXS": 4
      },
      "Button": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
        "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorActive": "#cf1322",
        "colorErrorBg": "#fff1f0",
        "colorErrorBorderHover": "#ff7875",
        "colorErrorHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLightSolid": "#ffffff",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "lineWidth": 1,
        "marginXS": 8,
        "opacityLoading": 0.65,
        "paddingContentHorizontal": 16,
        "paddingXS": 8
      },
      "Dropdown": {
        "colorBgElevated": "#ffffff",
        "colorError": "#ff4d4f",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLightSolid": "#ffffff",
        "borderRadiusLG": 8,
        "borderRadiusOuter": 4,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgActiveHover": "#EDE3CF",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlPaddingHorizontal": 12,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingXS": 8,
        "paddingXXS": 4,
        "sizePopupArrow": 16
      },
      "Menu": {
        "colorBgContainer": "#141414",
        "colorBgElevated": "#ffffff",
        "colorBgTextHover": "#ffffff1f",
        "colorError": "#ff4d4f",
        "colorErrorBg": "#fff1f0",
        "colorErrorHover": "#ff7875",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorPrimary": "#ffffff",
        "colorPrimaryBorder": "#E0CDA8",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "#ffffff",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(255,255,255,.25)",
        "colorTextLightSolid": "#ffffff",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActive": "#C39F59",
        "lineWidth": 1,
        "lineWidthBold": 2,
        "margin": 16,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingXL": 32,
        "paddingXS": 8
      },
      "Pagination": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
        "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "margin": 16,
        "marginSM": 12,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Steps": {
        "colorBgContainer": "#ffffff",
        "colorBorderBg": "#ffffff",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorError": "#ff4d4f",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorPrimary": "#B68A35",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLabel": "rgba(0, 0, 0, 0.65)",
        "colorTextLightSolid": "#ffffff",
        "colorTextQuaternary": "#4F4F4F",
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "lineWidthBold": 2,
        "margin": 16,
        "marginLG": 24,
        "marginSM": 12,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "AutoComplete": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorErrorHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "colorTextQuaternary": "#4F4F4F",
        "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
        "colorWarningHover": "#ffa940",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlHeightXS": 16,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Cascader": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorHighlight": "#ff7875",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorWhite": "#ffffff",
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlInteractiveSize": 16,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Checkbox": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorWhite": "#ffffff",
        "borderRadiusSM": 4,
        "controlInteractiveSize": 16,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "paddingXS": 8
      },
      "DatePicker": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorOutline": "#fff1f0",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorTextPlaceholder": "#4F4F4F",
        "colorWarning": "#fa8c16",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusOuter": 4,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4,
        "sizePopupArrow": 16
      },
      "Input": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorBorderHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "colorTextQuaternary": "#4F4F4F",
        "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
        "colorWarning": "#fa8c16",
        "colorWarningBorderHover": "#ffc069",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "InputNumber": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorBorderHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "colorWarning": "#fa8c16",
        "colorWarningBorderHover": "#ffc069",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Mentions": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorBorderHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "colorWarning": "#fa8c16",
        "colorWarningBorderHover": "#ffc069",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Radio": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLightSolid": "#ffffff",
        "colorWhite": "#ffffff",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActiveDisabled": "rgba(0, 0, 0, 0.15)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "lineWidth": 1,
        "marginXS": 8,
        "padding": 16,
        "paddingXS": 8
      },
      "Rate": {
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "controlHeightLG": 40,
        "lineWidth": 1,
        "marginXS": 8
      },
      "Select": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorErrorHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextPlaceholder": "#4F4F4F",
        "colorTextQuaternary": "#4F4F4F",
        "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
        "colorWarningHover": "#ffa940",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlHeightXS": 16,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Slider": {
        "colorBgContainer": "#ffffff",
        "colorBgElevated": "#ffffff",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillContentHover": "rgba(0, 0, 0, 0.15)",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryBorderHover": "#D1B580",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "lineWidth": 1
      },
      "Switch": {
        "colorBgContainer": "#ffffff",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorTextQuaternary": "#4F4F4F",
        "colorTextTertiary": "#4F4F4F",
        "colorWhite": "#ffffff",
        "controlHeight": 32,
        "marginXXS": 4,
        "opacityLoading": 0.65
      },
      "TimePicker": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorOutline": "#fff1f0",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorTextPlaceholder": "#4F4F4F",
        "colorWarning": "#fa8c16",
        "colorWarningOutline": "#fff7e6",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusOuter": 4,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlOutline": "rgba(5, 145, 255, 0.1)",
        "controlOutlineWidth": 2,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4,
        "sizePopupArrow": 16
      },
      "Transfer": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorLinkHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorWarning": "#fa8c16",
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgActiveHover": "#EDE3CF",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "margin": 16,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "TreeSelect": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgElevated": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLightSolid": "#ffffff",
        "colorWhite": "#ffffff",
        "borderRadius": 6,
        "borderRadiusSM": 4,
        "controlHeightSM": 24,
        "controlInteractiveSize": 16,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "paddingXS": 8
      },
      "Upload": {
        "colorBgMask": "rgba(0, 0, 0, 0.45)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorBg": "#fff1f0",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "borderRadiusLG": 8,
        "controlHeightLG": 40,
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "margin": 16,
        "marginXL": 32,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Avatar": {
        "colorBorderBg": "#ffffff",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorTextPlaceholder": "#4F4F4F",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "lineWidth": 1,
        "marginXS": 8,
        "marginXXS": 4
      },
      "Badge": {
        "colorBgContainer": "#ffffff",
        "colorBorderBg": "#ffffff",
        "colorError": "#ff4d4f",
        "colorErrorHover": "#ff7875",
        "colorPrimary": "#B68A35",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorTextPlaceholder": "#4F4F4F",
        "colorWarning": "#fa8c16",
        "borderRadiusSM": 4,
        "lineWidth": 1,
        "marginXS": 8,
        "paddingXS": 8
      },
      "Calendar": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "controlPaddingHorizontal": 12,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Card": {
        "colorBgContainer": "#ffffff",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorPrimary": "#B68A35",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "borderRadiusLG": 8,
        "lineWidth": 1,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Carousel": {
        "colorBgContainer": "#ffffff",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "marginXXS": 4
      },
      "Collapse": {
        "colorBgContainer": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "borderRadiusLG": 8,
        "lineWidth": 1,
        "marginSM": 12,
        "padding": 16,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Descriptions": {
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextSecondary": "rgba(0, 0, 0, 0.65)",
        "colorTextTertiary": "rgba(0, 0, 0, 0.45)",
        "borderRadiusLG": 8,
        "lineWidth": 1,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Empty": {
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "controlHeightLG": 40,
        "margin": 16,
        "marginXL": 32,
        "marginXS": 8,
        "opacityImage": 1
      },
      "Image": {
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgMask": "rgba(0, 0, 0, 0.45)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "controlHeightLG": 40,
        "marginSM": 12,
        "marginXXS": 4,
        "paddingSM": 12,
        "paddingXXS": 4
      },
      "List": {
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorPrimary": "#B68A35",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "lineWidth": 1,
        "margin": 16,
        "marginLG": 24,
        "marginSM": 12,
        "marginXXL": 48,
        "marginXXS": 4,
        "padding": 16,
        "paddingContentHorizontal": 16,
        "paddingContentHorizontalLG": 24,
        "paddingContentVertical": 12,
        "paddingContentVerticalLG": 16,
        "paddingContentVerticalSM": 8,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Popover": {
        "colorBgElevated": "#ffffff",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "borderRadiusLG": 8,
        "borderRadiusOuter": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "lineWidth": 1,
        "marginXS": 8,
        "padding": 16,
        "paddingSM": 12,
        "sizePopupArrow": 16
      },
      "QRCode": {
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorWhite": "#ffffff",
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "lineWidth": 1,
        "marginXS": 8,
        "paddingSM": 12
      },
      "Segmented": {
        "colorBgElevated": "#ffffff",
        "colorBgLayout": "rgba(0, 0, 0, 0.06)",
        "colorBorder": "rgba(0, 0, 0, 0.06)",
        "colorFill": "rgba(0, 0, 0, 0.15)",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLabel": "rgba(0, 0, 0, 0.65)",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlPaddingHorizontal": 12,
        "controlPaddingHorizontalSM": 8,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "marginSM": 12,
        "paddingXXS": 4
      },
      "Statistic": {
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "marginXXS": 4,
        "padding": 16
      },
      "Table": {
        "colorBgContainer": "#ffffff",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextPlaceholder": "#4F4F4F",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "controlInteractiveSize": 16,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgActiveHover": "#EDE3CF",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "margin": 16,
        "marginXXS": 4,
        "opacityLoading": 0.65,
        "padding": 16,
        "paddingContentVerticalLG": 16,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Tabs": {
        "colorBgContainer": "#ffffff",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "lineWidthBold": 2,
        "margin": 16,
        "marginSM": 12,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingLG": 24,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Tag": {
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorErrorBg": "#fff1f0",
        "colorErrorBorder": "#ffa39e",
        "colorFillQuaternary": "rgba(0, 0, 0, 0.02)",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorFillTertiary": "rgba(0, 0, 0, 0.04)",
        "colorInfo": "#B68A35",
        "colorInfoBg": "#F8F3EB",
        "colorInfoBorder": "#E0CDA8",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryHover": "#C39F59",
        "colorSuccess": "#52c41a",
        "colorSuccessBg": "#f6ffed",
        "colorSuccessBorder": "#b7eb8f",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorWarning": "#fa8c16",
        "colorWarningBg": "#fff7e6",
        "colorWarningBorder": "#ffd591",
        "borderRadiusSM": 4,
        "lineWidth": 1,
        "marginXS": 8,
        "paddingXXS": 4
      },
      "Timeline": {
        "colorBgContainer": "#ffffff",
        "colorError": "#ff4d4f",
        "colorPrimary": "#B68A35",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "controlHeightLG": 40,
        "lineWidth": 1,
        "lineWidthBold": 2,
        "margin": 16,
        "marginSM": 12,
        "marginXS": 8,
        "marginXXS": 4,
        "padding": 16,
        "paddingXXS": 4
      },
      "Tooltip": {
        "colorBgSpotlight": "#000",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "borderRadius": 6,
        "borderRadiusOuter": 4,
        "borderRadiusXS": 2,
        "controlHeight": 32,
        "paddingSM": 12,
        "paddingXS": 8,
        "sizePopupArrow": 16
      },
      "Tour": {
        "colorBgContainer": "#ffffff",
        "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
        "colorFill": "rgba(0, 0, 0, 0.15)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorPrimary": "#B68A35",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "colorWhite": "#ffffff",
        "borderRadius": 6,
        "borderRadiusLG": 8,
        "borderRadiusOuter": 4,
        "borderRadiusSM": 4,
        "borderRadiusXS": 2,
        "marginXS": 8,
        "padding": 16,
        "paddingXS": 8,
        "sizePopupArrow": 16
      },
      "Tree": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorError": "#ff4d4f",
        "colorLinkHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorWarning": "#fa8c16",
        "borderRadiusLG": 8,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlItemBgActive": "#F8F3EB",
        "controlItemBgActiveHover": "#EDE3CF",
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "margin": 16,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Drawer": {
        "colorBgElevated": "#ffffff",
        "colorBgMask": "rgba(0, 0, 0, 0.45)",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "lineWidth": 1,
        "marginSM": 12,
        "padding": 16,
        "paddingLG": 24,
        "paddingXS": 8
      },
      "Message": {
        "colorBgElevated": "#ffffff",
        "colorError": "#ff4d4f",
        "colorInfo": "#B68A35",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "borderRadiusLG": 8,
        "controlHeightLG": 40,
        "marginXS": 8,
        "paddingSM": 12,
        "paddingXS": 8
      },
      "Modal": {
        "colorBgElevated": "#ffffff",
        "colorBgMask": "rgba(0, 0, 0, 0.45)",
        "colorError": "#ff4d4f",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorInfo": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "lineWidth": 1,
        "margin": 16,
        "marginLG": 24,
        "marginSM": 12,
        "marginXS": 8,
        "padding": 16,
        "paddingContentHorizontalLG": 24,
        "paddingLG": 24,
        "paddingMD": 20,
        "paddingXS": 8
      },
      "Notification": {
        "colorBgElevated": "#ffffff",
        "colorError": "#ff4d4f",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "colorIconHover": "rgba(0, 0, 0, 0.88)",
        "colorInfo": "#B68A35",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeightLG": 40,
        "margin": 16,
        "marginLG": 24,
        "marginSM": 12,
        "marginXS": 8,
        "paddingContentHorizontalLG": 24,
        "paddingLG": 24,
        "paddingMD": 20
      },
      "Popconfirm": {
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "marginXS": 8,
        "marginXXS": 4
      },
      "Progress": {
        "colorBgContainer": "#ffffff",
        "colorError": "#ff4d4f",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorInfo": "#B68A35",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "marginXS": 8,
        "marginXXS": 4,
        "paddingXS": 8
      },
      "Result": {
        "colorError": "#ff4d4f",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorInfo": "#B68A35",
        "colorSuccess": "#52c41a",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "marginXS": 8,
        "padding": 16,
        "paddingLG": 24,
        "paddingXL": 32,
        "paddingXS": 8
      },
      "Skeleton": {
        "colorFill": "rgba(0, 0, 0, 0.15)",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "borderRadiusSM": 4,
        "controlHeight": 32,
        "controlHeightLG": 40,
        "controlHeightSM": 24,
        "controlHeightXS": 16,
        "marginLG": 24,
        "marginSM": 12,
        "marginXXS": 4,
        "padding": 16
      },
      "FloatButton": {
        "colorBgElevated": "#ffffff",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorPrimary": "#B68A35",
        "colorPrimaryHover": "#C39F59",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextLightSolid": "#ffffff",
        "borderRadiusLG": 8,
        "borderRadiusSM": 4,
        "controlHeightLG": 40,
        "controlItemBgHover": "rgba(0, 0, 0, 0.04)",
        "lineWidth": 1,
        "margin": 16,
        "marginLG": 24,
        "marginXXL": 48,
        "paddingXXS": 4
      },
      "Divider": {
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "lineWidth": 1,
        "margin": 16,
        "marginLG": 24,
        "marginXS": 8
      },
      "Typography": {
        "colorError": "#ff4d4f",
        "colorErrorActive": "#cf1322",
        "colorErrorHover": "#ff7875",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimaryHover": "#C39F59",
        "colorSuccess": "#52c41a",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "controlPaddingHorizontal": 12,
        "lineWidth": 1,
        "marginXS": 8,
        "marginXXS": 4,
        "paddingSM": 12,
        "paddingXS": 8,
        "paddingXXS": 4
      },
      "Spin": {
        "colorPrimary": "#B68A35"
      },
      "Alert": {
        "colorError": "#ff4d4f",
        "colorErrorBg": "#fff1f0",
        "colorErrorBorder": "#ffa39e",
        "colorInfo": "#B68A35",
        "colorInfoBg": "#F8F3EB",
        "colorInfoBorder": "#E0CDA8",
        "colorSuccess": "#52c41a",
        "colorSuccessBg": "#f6ffed",
        "colorSuccessBorder": "#b7eb8f",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextHeading": "rgba(0, 0, 0, 0.88)",
        "colorWarning": "#fa8c16",
        "colorWarningBg": "#fff7e6",
        "colorWarningBorder": "#ffd591",
        "colorIcon": "rgba(0, 0, 0, 0.45)",
        "borderRadiusLG": 8,
        "lineWidth": 1,
        "marginXS": 8,
        "marginSM": 12,
        "paddingMD": 20,
        "paddingContentHorizontalLG": 24
      },
      "Menu-custom": {
        "colorBgContainer": "#141414",
        "colorBgElevated": "#ffffff",
        "colorBgTextHover": "#ffffff1f",
        "colorError": "#ff4d4f",
        "colorErrorBg": "#fff1f0",
        "colorErrorHover": "#ff7875",
        "colorFillAlter": "rgba(0, 0, 0, 0.02)",
        "colorFillContent": "rgba(0, 0, 0, 0.06)",
        "colorPrimary": "#B68A35",
        "colorPrimaryBorder": "#E0CDA8",
        "colorSplit": "rgba(0, 0, 0, 0.06)",
        "colorText": "#ffffff",
        "colorTextDescription": "rgba(0, 0, 0, 0.45)",
        "colorTextDisabled": "rgba(255,255,255,.25)",
        "colorTextLightSolid": "#ffffff",
        "controlItemBgActive": "#F8F3EB"
      },
      "Segmented-custom": {
        "colorBgElevated": "#B68A35",
        "colorBgLayout": "#000",
        "colorFill": "rgba(0, 0, 0, 0.15)",
        "colorFillSecondary": "rgba(0, 0, 0, 0.06)",
        "colorText": "#ffffff",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLabel": "rgba(0, 0, 0, 0.65)",
        "colorBorder": "rgba(255, 255, 255, 0.25)"
      },
      "Button-custom": {
        "colorBgContainer": "#ffffff",
        "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
        "colorBgTextActive": "rgba(0, 0, 0, 0.15)",
        "colorBgTextHover": "rgba(0, 0, 0, 0.06)",
        "colorBorder": "rgba(0, 0, 0, 0.15)",
        "colorBorderSecondary": "rgba(0, 0, 0, 0.06)",
        "colorError": "#ff4d4f",
        "colorErrorActive": "#cf1322",
        "colorErrorBg": "#fff1f0",
        "colorErrorBorderHover": "#ff7875",
        "colorErrorHover": "#ff7875",
        "colorErrorOutline": "#fff1f0",
        "colorLink": "#B68A35",
        "colorLinkActive": "#9B752D",
        "colorLinkHover": "#C39F59",
        "colorPrimary": "#B68A35",
        "colorPrimaryActive": "#9B752D",
        "colorPrimaryBorder": "#E0CDA8",
        "colorPrimaryHover": "#C39F59",
        "colorText": "rgba(0, 0, 0, 0.88)",
        "colorTextDisabled": "rgba(0,0,0,0.25)",
        "colorTextLightSolid": "#ffffff"
      },
      "Map": {
        "Default": "#d6e4ff",
        "Active": "#ffc53d",
        "Border": "rgba(0, 0, 0, 0.15)"
      },
      "Icons-Dashboard-3": {
        "colorPrimayBase": "#B68A35",
        "colorPrimayBgHover": "#EDE3CF"
      }
    }
  },
  "$themes": {},
  "$metadata": {
    "undefined": {}
  }
};